### ISSUE TITLE
Not an issue, but a note :D

### ISSUE THREAD

**Issue by XxDuckyUxX** [mye-creator/Langwitch#1]
I want to create a game with this :heh:

I will learn this language and create a game using nothing but langwitch.

**Comment by mye-creator** [comment]
You can't do this right now, it's still on development. You can make only variables, math operations, print function and commentaries with ##

**Comment by mye-creator** [comment]
Oh, and hi ducky

**Comment by XxDuckyUxX** [comment]
With Variables and math operations, making a game isn't so hard :D

**Comment by mye-creator** [comment]
oh xD, yes ofc you can do math operations and variables!

**Comment by mye-creator** [comment]
Just a note

**Comment by mye-creator** [comment]
Was a note
